---
title: "Korean Immigrant Population in Cities"
author: "Joanna Choi"
description: "Varying Korean immigration population in cities with liberal constitutents and views"
output:
  distill::distill_article:
    self_contained: false
---



## Project thoughts

In my final project, I want to explore the effect of how liberal an urban city is on the population of Korean immigrants. With many immigration policies being correlated with liberal views, I wish to investgate whether there is a relationship that exists between thee score of how liberal the constituents of a city are, and the existing Korean immigrant population. I wish to also explore the correlation between cities and liberal views. Here are the sources I will use for this exploration:

1. [Pew Research Center - Korean in the U.S. Fact Sheet](https://www.pewresearch.org/social-trends/fact-sheet/asian-americans-koreans-in-the-u-s/) This data provides the cities with the highest number of Korean populations in the United States which is the outcome variable.

2. [The American Political Science Review - Representation in Municipal Govenment](https://www-jstor-org.ezp-prod1.hul.harvard.edu/stable/pdf/43654395.pdf?refreqid=excelsior%3A3d20248d6bf9a85ad9e0c8f94c4d4d66&ab_segments=&origin=&acceptTC=1) This is the data that delineates the liberal score of cities in the United States which is the explanatory variable.

3. [Pew Research Center - Political Polarization in the American Public](https://www.pewresearch.org/politics/2014/06/12/section-3-political-polarization-and-personal-life/) This data talks about the relationships between liberal views and urban cities which is the grouping variable.



